import { z } from "zod";

export const StageSchema = z.enum([
  "captured",
  "validated",
  "planned",
  "building",
  "launched",
  "growing",
  "killed",
  "archived",
]);
export type Stage = z.infer<typeof StageSchema>;

export const VentureSchema = z.object({
  id: z.string(),
  title: z.string(),
  description: z.string(),
  stage: StageSchema,
  verdictScore: z.number().min(0).max(100).nullable(),
  // Where the venture is actually being built -- a repo, a Lovable project, a
  // folder path. A plain text field, never an integration. Defaulted so
  // ventures saved before this field existed still parse. See
  // docs/plan/PHASE-07-build-stage.md.
  buildUrl: z.string().nullable().default(null),
  // Where the landing page form posts captured emails -- a Formspree-style
  // URL the user supplies. Absent means the CTA falls back to a mailto link;
  // never a dead button. See docs/plan/PHASE-08-launch-stage.md.
  emailCaptureUrl: z.string().nullable().default(null),
  // The live landing page URL from the deploy adapter (mock or Vercel).
  // Redeploying overwrites it -- never a history, just the current live URL.
  launchUrl: z.string().nullable().default(null),
  createdAt: z.string(),
  updatedAt: z.string(),
});
export type Venture = z.infer<typeof VentureSchema>;

export const ArtifactKindSchema = z.enum([
  "validation",
  "competitors",
  "plan",
  "mvp_scope",
  "landing_page",
  "content_calendar",
  "build_spec",
]);
export type ArtifactKind = z.infer<typeof ArtifactKindSchema>;

export const ArtifactSchema = z.object({
  id: z.string(),
  ventureId: z.string(),
  kind: ArtifactKindSchema,
  stage: StageSchema,
  content: z.unknown(),
  model: z.string(),
  costUsd: z.number(),
  // True when generated by the mock provider (no AI key configured). Must
  // never be mistaken for a real analysis -- see the workspace's demo marker.
  demo: z.boolean().default(false),
  createdAt: z.string(),
});
export type Artifact = z.infer<typeof ArtifactSchema>;

export const NucleusEventSchema = z.object({
  id: z.string(),
  ventureId: z.string().nullable(),
  type: z.string(),
  summary: z.string(),
  payload: z.unknown().optional(),
  createdAt: z.string(),
});
export type NucleusEvent = z.infer<typeof NucleusEventSchema>;

export const AiCallSchema = z.object({
  id: z.string(),
  task: z.string(),
  model: z.string(),
  promptTokens: z.number(),
  completionTokens: z.number(),
  costUsd: z.number(),
  cached: z.boolean(),
  ventureId: z.string().nullable(),
  createdAt: z.string(),
});
export type AiCall = z.infer<typeof AiCallSchema>;

// AI task output shapes. Defined here (client-safe) rather than in
// src/server/ai/tasks/, so the venture-result UI can import the type without
// importing server code -- the tasks themselves import these schemas back.
export const VerdictSchema = z.object({
  score: z.number().min(0).max(100),
  recommendation: z.enum(["build", "refine", "kill"]),
  headline: z.string().max(120),
  marketSize: z.object({
    estimate: z.string(),
    confidence: z.enum(["low", "medium", "high"]),
    reasoning: z.string(),
  }),
  audience: z.object({
    who: z.string(),
    painLevel: z.enum(["nice-to-have", "painful", "urgent"]),
  }),
  risks: z
    .array(z.object({ risk: z.string(), severity: z.enum(["low", "medium", "high"]) }))
    .min(2)
    .max(5),
  moat: z.string(),
  cheapestTest: z.string(),
  // Required, not optional -- an optional field gets omitted by the model.
  // A required one forces it to argue against the idea it just described.
  whyNot: z.string(),
});
export type Verdict = z.infer<typeof VerdictSchema>;

export const CompetitorsSchema = z.object({
  competitors: z
    .array(
      z.object({
        name: z.string(),
        whatTheyDo: z.string(),
        weakness: z.string(),
        howYouWin: z.string(),
      })
    )
    .min(3)
    .max(6),
  differentiationVerdict: z.string(),
  crowdedness: z.enum(["low", "medium", "high"]),
});
export type Competitors = z.infer<typeof CompetitorsSchema>;

export const PlanSchema = z.object({
  positioning: z.object({
    oneLiner: z.string().max(140),
    category: z.string(),
    wedge: z.string(),
  }),
  icp: z.object({
    who: z.string(),
    // Concrete named channels ("r/languagelearning"), never "social media" --
    // enforced in the prompt with a negative example, not just this schema.
    where: z.array(z.string()).min(2).max(5),
    currentSolution: z.string(),
    switchTrigger: z.string(),
  }),
  differentiation: z.array(z.string()).min(2).max(4),
  firstTenUsers: z.string(),
  successMetric: z.object({ metric: z.string(), target: z.string(), by: z.string() }),
  // Required, not optional -- same reasoning as Verdict.whyNot: a plan
  // without a stopping condition is how people burn a year on nothing.
  killCriteria: z.string(),
});
export type Plan = z.infer<typeof PlanSchema>;

export const MvpScopeSchema = z.object({
  coreLoop: z.string(),
  mustHave: z.array(z.object({ feature: z.string(), why: z.string() })).min(1).max(5),
  // At least 3 required -- the cuts are the scope. Capping mustHave alone
  // isn't enough; without a floor here explicitlyNot silently stays empty.
  explicitlyNot: z.array(z.string()).min(3),
  milestones: z
    .array(
      z.object({
        name: z.string(),
        outcome: z.string(),
        estimateDays: z.number().max(14),
      })
    )
    .min(3)
    .max(6),
  stack: z.object({ recommendation: z.string(), reasoning: z.string() }),
  riskiestAssumption: z.string(),
});
export type MvpScope = z.infer<typeof MvpScopeSchema>;

// One checkable task per MVP milestone. Created by expanding milestones on
// planned -> building; never by an AI call -- the plan already contains the
// content. See docs/plan/PHASE-07-build-stage.md.
export const BuildTaskSchema = z.object({
  id: z.string(),
  ventureId: z.string(),
  milestone: z.string(),
  title: z.string(),
  done: z.boolean(),
  createdAt: z.string(),
  doneAt: z.string().nullable(),
});
export type BuildTask = z.infer<typeof BuildTaskSchema>;

// The artifact that leaves Nucleus and enters a build tool -- three export
// formats render the same data. See docs/plan/PHASE-07-build-stage.md.
export const BuildSpecSchema = z.object({
  summary: z.string(),
  userStories: z
    .array(
      z.object({
        as: z.string(),
        iWant: z.string(),
        soThat: z.string(),
        acceptance: z.array(z.string()).min(1),
      })
    )
    .min(3)
    .max(10),
  dataModel: z.array(z.object({ entity: z.string(), fields: z.array(z.string()) })),
  screens: z.array(z.object({ name: z.string(), purpose: z.string(), elements: z.array(z.string()) })),
  outOfScope: z.array(z.string()).min(3),
  // The literal first thing to build -- naming it removes the hardest part
  // of starting, which is starting.
  firstCommit: z.string(),
});
export type BuildSpec = z.infer<typeof BuildSpecSchema>;

// The model writes copy, never HTML -- a hand-built template renders it.
// Length caps are load-bearing: an unbounded headline field returns a
// paragraph. See docs/plan/PHASE-08-launch-stage.md.
export const LandingSchema = z.object({
  headline: z.string().max(70),
  subhead: z.string().max(160),
  problem: z.string(),
  solution: z.string(),
  benefits: z.array(z.object({ title: z.string().max(40), body: z.string() })).length(3),
  socialProofPlaceholder: z.string(),
  cta: z.object({ label: z.string().max(25), subtext: z.string() }),
  faq: z.array(z.object({ q: z.string(), a: z.string() })).min(3).max(5),
  seo: z.object({ title: z.string().max(60), description: z.string().max(155) }),
});
export type Landing = z.infer<typeof LandingSchema>;
